version: '3.1'

services:
  db:
    image: postgres:16
    container_name: fisherman-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fisherman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - fisherman-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fisherman-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fisherman
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  fisherman-data:
